
# Gem::Specification for Ambitious-activerecord-0.1.3
# Originally generated by Echoe

Gem::Specification.new do |s|
  s.name = %q{ambitious-activerecord}
  s.version = "0.1.3"

  s.specification_version = 2 if s.respond_to? :specification_version=

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Wanstrath"]
  s.date = %q{2008-04-26}
  s.description = %q{An ambitious adapter for ActiveRecord}
  s.email = %q{chris@ozmm.org}
  s.extra_rdoc_files = ["lib/ambition/adapters/active_record/base.rb", "lib/ambition/adapters/active_record/query.rb", "lib/ambition/adapters/active_record/select.rb", "lib/ambition/adapters/active_record/slice.rb", "lib/ambition/adapters/active_record/sort.rb", "lib/ambition/adapters/active_record/statements.rb", "lib/ambition/adapters/active_record.rb"]
  s.files = ["lib/ambition/adapters/active_record/base.rb", "lib/ambition/adapters/active_record/query.rb", "lib/ambition/adapters/active_record/select.rb", "lib/ambition/adapters/active_record/slice.rb", "lib/ambition/adapters/active_record/sort.rb", "lib/ambition/adapters/active_record/statements.rb", "lib/ambition/adapters/active_record.rb", "test/benchmark.rb", "test/chaining_test.rb", "test/count_test.rb", "test/enumerable_test.rb", "test/helper.rb", "test/join_test.rb", "test/profiler.rb", "test/ruby_test.rb", "test/select_test.rb", "test/slice_test.rb", "test/sort_test.rb", "test/source_test.rb", "test/types_test.rb", "Manifest", "ambitious-activerecord.gemspec"]
  s.has_rdoc = true
  s.homepage = %q{http://ambition.rubyforge.org/}
  s.rdoc_options = ["--line-numbers", "--inline-source", "--title", "Ambitious-activerecord", "--main", "README"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{ambition}
  s.rubygems_version = %q{1.0.1}
  s.summary = %q{An ambitious adapter for ActiveRecord}
  s.test_files = ["test/chaining_test.rb", "test/count_test.rb", "test/enumerable_test.rb", "test/join_test.rb", "test/ruby_test.rb", "test/select_test.rb", "test/slice_test.rb", "test/sort_test.rb", "test/source_test.rb", "test/types_test.rb"]

  s.add_dependency(%q<activerecord>, [">= 1.15.6"])
  s.add_dependency(%q<ambition>, [">= 0.5.3"])
end


# # Original Rakefile source (requires the Echoe gem):
# 
# require 'rake'
# 
# Version = '0.1.3'
# 
# begin
#   require 'rubygems'
#   gem 'echoe', '>=2.7'
#   ENV['RUBY_FLAGS'] = ""
#   require 'echoe'
# 
#   Echoe.new('ambitious-activerecord') do |p|
#     p.dependencies  << 'activerecord >=1.15.6'
#     p.summary        = "An ambitious adapter for ActiveRecord"
#     p.author         = 'Chris Wanstrath'
#     p.email          = "chris@ozmm.org"
# 
#     p.project        = 'ambition'
#     p.url            = "http://ambition.rubyforge.org/"
#     p.test_pattern   = 'test/*_test.rb'
#     p.version        = Version
#     p.dependencies  << 'ambition >=0.5.3'
#   end
# 
# rescue LoadError 
#   puts "Not doing any of the Echoe gemmy stuff, because you don't have the specified gem versions"
# 
#   require 'rake/testtask'
#   Rake::TestTask.new do |t|
#     t.pattern = "test/*_test.rb"
#   end
# end
# 
# desc 'Install as a gem'
# task :install_gem do
#   puts `rake manifest package && gem install pkg/ambitious-activerecord-#{Version}.gem`
# end
# 
# task :default => :test 
# 
